Repository EnvEduPNU/EnvEdu_Server, pull requests merged in 2023-03, with the labels that each got.

#11 Environment/maven gitignore
  .gitignore
Labels: environment

#12 Environment/maven gitignore
  .gitignore
Labels: environment

#13 [환경설정] : gitignore 내용 추가
  .gitignore
Labels: environment

#16 14 test
  README.md
Labels: wontfix

#20 Feature/#19/maven ci/201724554
  .github/workflows/maven.yml
Labels: backend, env

#21 feature/#19/maven CI/201724554
  .github/workflows/maven.yml
Labels: backend, env

#23 Feature/#19/maven ci/201724554
  .github/workflows/maven.yml
Labels: backend, env

#25 #19-env/action 수동 실행 추가
  .github/workflows/maven.yml
Labels: backend, env

#26 Feature/#19/maven ci/201724554
  .github/workflows/maven.yml
Labels: backend, env

#27 Develop
  .github/workflows/maven.yml
Labels: backend, env

#28 #19-env/S3을 이용한 CI/CD 추가
  .github/workflows/maven.yml
  appspec.yml
  scripts/deploy.sh
Labels: backend, env

#29 Feature/#19/maven ci/201724554
  .github/workflows/maven.yml
  appspec.yml
  scripts/deploy.sh
Labels: backend, env

#30 S3를 이용한 CI/CD 추가
  .github/workflows/maven.yml
  appspec.yml
  scripts/deploy.sh
Labels: backend, env

#32 Feature/#19/maven ci/201724554
  .github/workflows/maven.yml
Labels: backend, env

#33 maven.yml 수정
  .github/workflows/maven.yml
Labels: backend, env
