Repository EnvEduPNU/EnvEdu_Server, pull requests merged in 2023-05, with the labels that each got.

#119 2023/05/05
  src/main/java/com/example/demo/DTO/AddMACDTO.java
  src/main/java/com/example/demo/device/controller/UserDeviceController.java
  src/main/java/com/example/demo/device/model/UserDevice.java
  src/main/java/com/example/demo/device/service/UserDeviceService.java
  src/main/java/com/example/demo/seed/socket/config/DeviceSocketInterceptor.java
  src/main/java/com/example/demo/seed/socket/config/SocketConnectionInterceptor.java
  src/main/java/com/example/demo/seed/socket/config/WebSocketConfig.java
Labels: feat, refactor, backend

#120 feature/#109/Readme/20124554
  README.md
Labels: backend, doc

#121 2023/05/07
  README.md
Labels: backend, doc

#123 feature/#122/redundant code/201724554
  src/main/java/com/example/demo/DTO/AddMACDTO.java
  src/main/java/com/example/demo/DTO/MacListDTO.java
  src/main/java/com/example/demo/admin/model/Admin.java
  src/main/java/com/example/demo/device/controller/UserDeviceController.java
  src/main/java/com/example/demo/device/dto/request/AddMACDTO.java
  src/main/java/com/example/demo/device/model/UserDevice.java
  src/main/java/com/example/demo/device/service/UserDeviceService.java
  src/main/java/com/example/demo/security/config/AuthenticationFilterApply.java
  src/main/java/com/example/demo/security/config/AuthorizationFilterApply.java
  src/main/java/com/example/demo/security/config/SecurityConfig.java
  src/main/java/com/example/demo/seed/socket/config/WebSocketConfig.java
  src/main/java/com/example/demo/token/model/AccessToken.java
  src/main/java/com/example/demo/token/model/RefreshToken.java
  src/main/java/com/example/demo/token/repository/RefreshTokenRepository.java
  src/main/java/com/example/demo/user/controller/UserLogoutController.java
  src/main/java/com/example/demo/user/controller/UserRegisterController.java
  src/main/java/com/example/demo/user/service/UserService.java
Labels: refactor, backend

#124 2023/05/08
  src/main/java/com/example/demo/DTO/AddMACDTO.java
  src/main/java/com/example/demo/DTO/MacListDTO.java
  src/main/java/com/example/demo/admin/model/Admin.java
  src/main/java/com/example/demo/device/controller/UserDeviceController.java
  src/main/java/com/example/demo/device/dto/request/AddMACDTO.java
  src/main/java/com/example/demo/device/model/UserDevice.java
  src/main/java/com/example/demo/device/service/UserDeviceService.java
  src/main/java/com/example/demo/security/config/AuthenticationFilterApply.java
  src/main/java/com/example/demo/security/config/AuthorizationFilterApply.java
  src/main/java/com/example/demo/security/config/SecurityConfig.java
  src/main/java/com/example/demo/seed/socket/config/WebSocketConfig.java
  src/main/java/com/example/demo/token/model/AccessToken.java
  src/main/java/com/example/demo/token/model/RefreshToken.java
  src/main/java/com/example/demo/token/repository/RefreshTokenRepository.java
  src/main/java/com/example/demo/user/controller/UserLogoutController.java
  src/main/java/com/example/demo/user/controller/UserRegisterController.java
  src/main/java/com/example/demo/user/service/UserService.java
Labels: refactor, backend

#129 feature/#111/seperatePrincipals/201724554
  src/main/java/com/example/demo/security/config/AuthenticationFilter.java
  src/main/java/com/example/demo/security/config/AuthorizationFilter.java
  src/main/java/com/example/demo/security/config/CorsConfig.java
  src/main/java/com/example/demo/security/jwt/JwtUtil.java
  src/main/java/com/example/demo/security/jwt/Properties.java
  src/main/java/com/example/demo/security/principal/AuthenticationFilterPrincipalDetails.java
  src/main/java/com/example/demo/security/principal/AuthenticationFilterPrincipalDetailsService.java
  src/main/java/com/example/demo/security/principal/AuthorizationFilterPrincipalDetails.java
  src/main/java/com/example/demo/security/principal/PrincipalDetails.java
  src/main/java/com/example/demo/security/principal/PrincipalDetailsService.java
Labels: refactor, backend

#128 공지 게시판, Open Api, 차트 생성
  pom.xml
  src/main/java/com/example/demo/boards/controller/BoardController.java
  src/main/java/com/example/demo/boards/domain/BoardDTO.java
  src/main/java/com/example/demo/chart/controller/ChartController.java
  src/main/java/com/example/demo/chart/service/ChartService.java
  src/main/java/com/example/demo/openapi/controller/OpenApiController.java
  src/main/java/com/example/demo/openapi/dto/AirQualityDTO.java
  src/main/java/com/example/demo/openapi/dto/OceanQualityDTO.java
  src/main/java/com/example/demo/openapi/dto/OpenApiParam.java
  src/main/java/com/example/demo/openapi/model/entity/AirQuality.java
  src/main/java/com/example/demo/openapi/model/entity/OceanQuality.java
  src/main/java/com/example/demo/openapi/model/parent/AirQualityParent.java
  src/main/java/com/example/demo/openapi/model/parent/OceanQualityParent.java
  src/main/java/com/example/demo/openapi/module/OpenApiRequest.java
  src/main/java/com/example/demo/openapi/service/OpenApiService.java
  src/main/java/com/example/demo/security/config/SecurityConfig.java
  src/main/resources/templates/PopupChart.html
  src/main/resources/templates/SampleChart.html
Labels: feat, backend, add

#131 feature/#117/check dupicate educator student/201724554
  pom.xml
  src/main/java/com/example/demo/user/controller/UserRegisterController.java
  src/main/java/com/example/demo/user/dto/request/StudentAddDTO.java
  src/main/java/com/example/demo/user/dto/response/Student_EducatorDTO.java
  src/main/java/com/example/demo/user/model/entity/Student_Educator.java
  src/main/java/com/example/demo/user/service/UserService.java
  src/test/java/com/example/demo/user/controller/UserControllerTest.java
Labels: feat, backend
